name: CI to Docker hub 

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Go project --> Dockerhub
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@master

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_AUTH_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_REPOSITORY }}:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}