name: Go

on:
  push:
    branches: [ main ]

jobs:

 build-and-push:
    name: Go project --> Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

# build golang project
    - name: run
      uses: cedrickring/golang-action@1.6.0

# push to dockerhub
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_AUTH_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        tags: ${{ secrets.DOCKER_REPOSITORY }}:latest


